application:
  name: sonarqube
  createNamespace: ###ZARF_VAR_SONARQUBE_CREATE_NAMESPACE###
  namespace: sonarqube
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/sonarqube.git
  ref:
    tag: 8.0.0-bb.1
  values: |
    ###ZARF_VAR_SONARQUBE_VALUES###
  dependsOn:
    ###ZARF_VAR_GITLAB_DEPENDS_ON###
