application:
  name: sonarqube
  createNamespace: ###ZARF_VAR_SONARQUBE_CREATE_NAMESPACE###
  namespace: sonarqube
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/sonarqube.git
  ref:
    tag: 8.0.1-bb.2
  values: |
    ###ZARF_VAR_SONARQUBE_VALUES###
  dependsOn:
    ###ZARF_VAR_SONARQUBE_DEPENDS_ON###
