application:
  name: sonarqube
  createNamespace: ###ZARF_VAR_SONARQUBE_CREATE_NAMESPACE###
  namespace: sonarqube
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/sonarqube.git
  ref:
    # renovate: datasource=gitlab-tags depName=big-bang/product/packages/sonarqube versioning=loose registryUrl=https://repo1.dso.mil
    tag: 8.0.1-bb.2
  dependsOn:
    ###ZARF_VAR_SONARQUBE_DEPENDS_ON###
  baseValues:
    # hostname is deprecated and replaced with domain. But if hostname exists then use it.
    domain: ###ZARF_VAR_DOMAIN###

    # Define variables to help with conditionals later

    OpenShift:
      enabled: false

    istio:
      enabled: true
      sonarqube:
        gateways:
        - istio-system/tenant
      injection: enabled

    monitoring:
      enabled: true

    networkPolicies:
      enabled: true
      ingressLabels:
        app: null
        istio: null

    networkPolicy:
      enabled: true
      additionalNetworkPolicys:
        ingress:
        - from:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: gitlab-runner-sandbox
            podSelector: {}
          ports:
          - port: 9000
            protocol: TCP
        egress:
        - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: gitlab
            podSelector:
              matchLabels:
                app: webservice
        - to:
          - namespaceSelector:
              matchLabels:
                kubernetes.io/metadata.name: gitlab-runner-sandbox
            podSelector: {}
        podSelector:
          matchLabels: {}
        policyTypes:
        - Egress
        - Ingress

    image:
      pullPolicy: IfNotPresent
    annotations:
      bigbang.dev/istioVersion: ###ZARF_VAR_ISTIO_VERSION###

    jdbcOverwrite:
      enable: true
      jdbcUrl: jdbc:postgresql://postgresql.sonarqube-db.svc.cluster.local:5432/###ZARF_VAR_SONARQUBE_DB###
      jdbcUsername: sonarqube
      jdbcSecretName: sonarqube-postgres
      jdbcSecretPasswordKey: password

    postgresql:
      # Use internal database, defaults are fine
      enabled: false
      master:
        podAnnotations:
          bigbang.dev/istioVersion: ###ZARF_VAR_ISTIO_VERSION###
      slave:
        podAnnotations:
          bigbang.dev/istioVersion: ###ZARF_VAR_ISTIO_VERSION###
      postgresqlServer: sonarqube-postgres
      existingSecret: "sonarqube-postgres"
      existingSecretPasswordKey: "password"
      postgresqlUsername: "sonarqube"
      postgresqlDatabase: "###ZARF_VAR_SONARQUBE_DB###"
      service:
        port: 5432
