application:
  name: sonarqube
  namespace: sonarqube
  path: chart
  repository: https://repo1.dso.mil/big-bang/product/packages/sonarqube.git
  tag: 8.0.0-bb.1
  values: |
    ###ZARF_VAR_GITLAB_RUNNER_VALUES###
