# hostname is deprecated and replaced with domain. But if hostname exists then use it.
domain: bigbang.dev

# Define variables to help with conditionals later

OpenShift:
  enabled: false

istio:
  enabled: true
  sonarqube:
    gateways:
    - istio-system/tenant
  injection: enabled

monitoring:
  enabled: true

networkPolicies:
  enabled: true
  ingressLabels:
    app: null
    istio: null

image:
  pullPolicy: IfNotPresent
  pullSecret: private-registry
postgresql:
  # Use internal database, defaults are fine
  enabled: true
  service:
    port: 5432
